name: Build and Deploy Docs

on:
  workflow_dispatch:
  push:
    branches: [ master ]

permissions:
  contents: write  # <-- This grants the token permission to push changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Publish with dotnet
      run: dotnet publish -c Release -o public -p:GHPages=true 
      working-directory: ./examples/Demos

    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4  # Use latest stable version
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GitHub Token
        BRANCH: gh-pages
        FOLDER: examples/Demos/public/wwwroot
        CLEAN: true
