name: Deploy WASM Demo

on:
  push:
    branches:
      - main  # Läuft bei Pushes auf den main-Branch

  workflow_dispatch:  # Ermöglicht manuelles Ausführen des Workflows

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish Blazor WebAssembly
        run: dotnet publish examples/WasmExample/WasmExample/WasmExample.csproj -c Release -o output --nologo

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/wwwroot

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
